// Journey UI behaviour. GENERATED by scripts/gen_journey.py from design/chg-journey.html. Scoped to `root` so it can
// mount and unmount inside React. Returns a cleanup function.
// Responsive layer: fit() scales the 1440x900 canvas to fill any screen, and switches
// to the phone layout (stage[data-mode="m"]) under 900px wide or in portrait.
export function initJourney(root) {
  var cleanups = [];
  var zoomTimer = null;
  cleanups.push(function () { if (zoomTimer) clearTimeout(zoomTimer); });


  /* ================= DATA ================= */
  // Where each stop sits along the route, as % of the path length.
  var ROUTE_PCT = [13.07, 31.62, 50.07, 68.28, 84.22, 100];
  var STOPS = [
    { id: 'about',    num: '01', name: 'About',    title: 'Who’s building it',            teaser: 'psychology → systems',  x: 360,  y: 250 },
    { id: 'work',     num: '02', name: 'Work',     title: 'Selected work',                teaser: '6 projects, live',      x: 590,  y: 640 },
    { id: 'services', num: '03', name: 'Services', title: 'Three ways to work together',  teaser: 'build · rescue · hire', x: 830,  y: 260 },
    { id: 'stack',    num: '04', name: 'Stack',    title: 'The toolkit',                  teaser: '6 layers, one system',  x: 1060, y: 640 },
    { id: 'clients',  num: '05', name: 'Clients',  title: 'What clients say',             teaser: 'proof, in their words', x: 1250, y: 300 },
    { id: 'contact',  num: '06', name: 'Contact',  title: 'Start your build',             teaser: 'your move',             x: 1330, y: 690 }
  ];
  var PROJECTS = [
    { cat: 'STUDIO OPERATIONS PLATFORM', name: 'Dance Studio Portal', mono: 'DS', tint: '#B8466E', domain: 'studio.capitalcoredance.com', url: 'https://studio.capitalcoredance.com/',
      desc: 'The live operating system for a dance studio: enrollment, trials, recurring tuition billing with PayPal, parent and instructor portals, website intake, and family email campaigns. Real auth, row-level security, real money.',
      outcome: 'Runs the studio’s day to day, in production.', tags: ['Next.js', 'Supabase RLS', 'PayPal', 'Resend'] },
    { cat: 'RESCUE & REBUILD', name: 'Bounce FX', mono: 'BFX', tint: '#8C6A28', domain: 'bouncefxpartyrentals.com', url: 'https://www.bouncefxpartyrentals.com/',
      desc: 'Moved a party rental business off Squarespace onto a custom booking site and admin portal: live inventory, bundle slots, Stripe checkout, and a CRM built from their old order history.',
      outcome: 'Booking, payments, and admin in one system they own.', tags: ['Next.js', 'Stripe', 'Admin Portal'] },
    { cat: 'APPRENTICESHIP MANAGEMENT', name: 'PathBuilders', mono: 'PB', tint: '#3E6A7A', domain: 'pathbuilders.vercel.app', url: 'https://pathbuilders.vercel.app/',
      desc: 'Apprenticeship management platform for HVAC, electrical, and plumbing programs. Admin, instructor, employer, and apprentice portals with OJT timesheets, attendance, and hour ledgers. Public mock with fictional data, so click around.',
      outcome: '247 mock apprentices, 62 employers, one connected system.', tags: ['Next.js 16', 'React 19', 'Data Modeling'] },
    { cat: 'INSURANCE OPERATIONS PLATFORM', name: 'Villa Concierge Co', mono: 'VC', tint: '#211C18', domain: 'villa-group-conceirge2.vercel.app', url: 'https://villa-group-conceirge2.vercel.app/',
      desc: 'Operations system for an insurance relocation housing firm. Placements, housing inventory, carrier and adjuster contacts, and billing for ALE claims in one interface.',
      outcome: 'Replaced 3 separate tools with one unified platform.', tags: ['Operations', 'React', 'Supabase'] },
    { cat: 'AI PERSONAL GROWTH APP', name: 'Seal the Leak', mono: 'STL', tint: '#6E4A7E', domain: 'nicolesprojectapp.vercel.app', url: 'https://nicolesprojectapp.vercel.app/',
      desc: 'A daily clarity app and step-by-step reset program personalized to your energy archetype, with AI-generated daily guidance.',
      outcome: '365 AI-personalized daily cards delivered on demand.', tags: ['AI', 'Next.js', 'Supabase'] },
    { cat: 'AI BUILD LAB', name: 'Stackd Studios', mono: 'SS', tint: '#4F6B49', domain: 'stackdstudiosai.com', url: 'https://www.stackdstudiosai.com/',
      desc: 'My build lab. Where I design and ship AI products, agent tooling, and client systems, from first idea to live product.',
      outcome: 'Idea to live product in under 6 weeks.', tags: ['Strategy', 'Product', 'AI'] }
  ];
  var STACK = [
    { name: 'AI & Agents', items: [['Claude (Anthropic)', 'Opus · Sonnet · Haiku'], ['Claude Agent SDK', 'Tool use · Caching · Agents'], ['Claude Code', 'Skills · Hooks · Subagents'], ['Multi-Agent Orchestration', 'Lead + worker harnesses'], ['MCP', 'Custom servers & integrations'], ['Vercel AI SDK', 'Streaming · UI integration'], ['OpenAI · Gemini', 'When the job calls for it']] },
    { name: 'Frontend', items: [['Next.js', 'App Router · 14 to 16'], ['React', '18 & 19 · Server Components'], ['TypeScript', 'Type-safe everything'], ['Tailwind CSS', 'v3 & v4'], ['shadcn/ui + Radix', 'Accessible components'], ['Framer Motion', 'Animation & transitions'], ['Recharts', 'Dashboards & reporting']] },
    { name: 'Backend & Data', items: [['Supabase', 'Postgres · Auth · Storage'], ['Row-Level Security', 'Multi-role access done right'], ['PostgreSQL', 'Schema design · migrations'], ['Node.js', 'API routes · server actions'], ['Webhooks & Intake Pipes', 'System-to-system data'], ['Python', 'Scripting · data jobs']] },
    { name: 'Payments & Comms', items: [['Stripe', 'Checkout · Webhooks · Subscriptions'], ['PayPal', 'Vaulted cards · Invoicing'], ['Resend', 'Transactional & campaign email'], ['Google Workspace', 'Sheets · Drive · Gmail APIs']] },
    { name: 'Deploy & Ops', items: [['Vercel', 'Hosting · CI/CD · Env'], ['GitHub', 'Version control · Actions'], ['Cloudflare', 'DNS · Workers'], ['Security Hardening', 'Auth · RLS · dependency audits']] },
    { name: 'Games & 3D', items: [['Phaser 3', '2D sims · React + Vite'], ['Unity', '3D management sims'], ['Roblox (Luau)', 'Rojo toolchain'], ['Blender', 'Assets & scene work']] }
  ];

  /* ================= STATE ================= */
  var state = { scene: 'office', zooming: false, stop: -1, last: -1, visited: {}, project: 0, tab: 0, mobile: false, vw: 0, vh: 0 };
  var $ = function (sel, scope) { return (scope || root).querySelector(sel); };
  var el = function (tag, cls, text) { var n = document.createElement(tag); if (cls) n.className = cls; if (text != null) n.textContent = text; return n; };

  /* ================= FIT STAGE TO WINDOW ================= */
  var stage = $('#stage');
  // Phone / portrait-tablet layout below this width, or when taller than wide.
  function isMobile(vw, vh) { return vw < 900 || vw / vh < 1.1; }
  function place(frame, s, tx, ty) {
    if (frame) frame.style.transform = 'translate(' + tx + 'px,' + ty + 'px) scale(' + s + ')';
  }
  function fit() {
    var vw = window.innerWidth, vh = window.innerHeight;
    state.vw = vw; state.vh = vh;
    state.mobile = isMobile(vw, vh);
    stage.dataset.mode = state.mobile ? 'm' : 'd';
    var s, tx, ty;
    if (state.mobile) {
      // crop the office around the monitor, which sits at (760, 422) on the canvas
      var short = vh < 500;
      s = Math.min(vw / 520, (vh * (short ? 0.36 : 0.42)) / 254, 1.25);
      tx = vw / 2 - 760 * s;
      ty = vh * (short ? 0.30 : 0.37) - 422 * s;
      stage.style.setProperty('--ox', '0px');
      stage.style.setProperty('--oy', '0px');
    } else {
      // contain the canvas, let backgrounds and chrome run to the real edges
      s = Math.min(vw / 1440, vh / 900);
      tx = (vw - 1440 * s) / 2;
      ty = (vh - 900 * s) / 2;
      stage.style.setProperty('--ox', (tx / s) + 'px');
      stage.style.setProperty('--oy', (ty / s) + 'px');
    }
    place($('#officeFrame'), s, tx, ty);
    if (!state.mobile) place($('#insideFrame'), s, tx, ty);
    var k = Math.min(vw / 1400, (vh * 0.34) / 900);
    state.mapK = k;
    stage.style.setProperty('--band', (60 + 900 * k) + 'px');
    render(false);
  }
  window.addEventListener('resize', fit);
  cleanups.push(function () { window.removeEventListener('resize', fit); });

  /* ================= OFFICE CLOCK ================= */
  function tick() {
    var d = new Date(), m = d.getMinutes(), h = d.getHours() % 12;
    var hh = $('#hourHand'), mm = $('#minHand');
    if (hh) hh.setAttribute('transform', 'rotate(' + (h * 30 + m * 0.5) + ' 1360 180)');
    if (mm) mm.setAttribute('transform', 'rotate(' + (m * 6) + ' 1360 180)');
  }
  tick();
  var clock = setInterval(tick, 15000);
  cleanups.push(function () { clearInterval(clock); });

  /* ================= SCENE CHANGES ================= */
  var officeScene = $('#officeScene'), office = $('#office'), mount = $('#insideMount');

  function enter(thenStop) {
    if (state.zooming) return;
    state.zooming = true;
    office.classList.add('zoom');
    officeScene.classList.add('zooming');
    zoomTimer = setTimeout(function () {
      officeScene.hidden = true;
      mount.innerHTML = '';
      mount.appendChild($('#tpl-inside').content.cloneNode(true));
      state.scene = 'inside';
      state.stop = -1;
      buildInside();
      fit();
      state.zooming = false;
      if (thenStop != null) { go(thenStop); return; }
      var start = $('[data-action="start"]');
      if (start) start.focus({ preventScroll: true });
    }, 1700);
  }

  function exit() {
    state.scene = 'office';
    state.stop = -1;
    mount.innerHTML = '';
    officeScene.hidden = false;
    office.classList.add('zoom');
    void office.offsetWidth;               // lock in the zoomed frame
    setTimeout(function () { office.classList.remove('zoom'); officeScene.classList.remove('zooming'); }, 30);
  }

  /* ================= INSIDE: BUILD ================= */
  function buildInside() {
    var nodes = $('#nodes'), rail = $('#rail');
    STOPS.forEach(function (s, i) {
      var n = el('div', 'node');
      n.style.left = (s.x - 110) + 'px';
      n.style.top = (s.y - 36) + 'px';
      n.style.animationDelay = (1.1 + i * 0.14).toFixed(2) + 's';
      var b = el('button', 'nbtn', s.num);
      b.setAttribute('aria-label', 'Go to stop ' + s.num + ', ' + s.name);
      b.dataset.action = 'go'; b.dataset.stop = i;
      var lab = el('div', 'nlab');
      var t1 = el('span', null, s.name); t1.style.cssText = 'font-size:16px;font-weight:600;color:#EDE4D6';
      var t2 = el('span', 'mono', s.teaser); t2.style.cssText = 'font-size:11px;color:#B9AE9F';
      lab.append(t1, t2);
      n.append(b, lab);
      nodes.appendChild(n);

      var r = el('button', 'rb');
      r.dataset.action = 'go'; r.dataset.stop = i;
      r.append(el('span', 'n', s.num), el('span', null, s.name), el('span', 'bar'));
      rail.appendChild(r);
    });
  }

  /* ================= INSIDE: RENDER ================= */
  function go(i) {
    var changed = state.stop !== i;
    state.stop = i; state.last = i; state.visited[i] = true;
    render(changed);
  }

  function render(swapContent) {
    if (state.scene !== 'inside') return;
    var stop = state.stop, here = stop >= 0 ? stop : state.last;
    var visitedCount = Object.keys(state.visited).length;

    // map pan + traveller
    var map = $('#map');
    if (state.mobile) {
      var k = state.mapK || 0.25;
      map.style.transform = 'translate(' + ((state.vw - 1440 * k) / 2) + 'px,56px) scale(' + k + ')';
    } else {
      map.style.transform = stop >= 0 ? 'translate(' + (290 - STOPS[stop].x) + 'px,' + (440 - STOPS[stop].y) + 'px)' : 'translate(0px,0px)';
    }
    var insideEl = $('.inside');
    if (insideEl) insideEl.classList.toggle('has-panel', stop >= 0);
    var pct = here >= 0 ? ROUTE_PCT[here] : 0;
    $('#you').style.offsetDistance = pct + '%';
    $('#progressPath').style.strokeDashoffset = 100 - pct;

    // nodes + rail
    root.querySelectorAll('#nodes .node').forEach(function (n, i) {
      n.classList.toggle('cur', stop === i);
      n.classList.toggle('done', stop !== i && !!state.visited[i]);
      n.classList.toggle('dim', stop >= 0 && stop !== i);
    });
    root.querySelectorAll('#rail .rb').forEach(function (r, i) {
      r.classList.toggle('cur', stop === i);
      r.classList.toggle('done', stop !== i && !!state.visited[i]);
    });

    // top bar
    $('#crumb').textContent = stop >= 0 ? '/' + STOPS[stop].num + '-' + STOPS[stop].id : '';
    $('#progress').textContent = visitedCount + ' / 6 explored';

    // intro card
    var nextUnseen = 0; while (nextUnseen < 5 && state.visited[nextUnseen]) nextUnseen++;
    $('#intro').hidden = stop >= 0;
    $('#startLabel').textContent = visitedCount === 0 ? 'Start the journey' : (visitedCount >= 6 ? 'Revisit the journey' : 'Continue to ' + STOPS[nextUnseen].name);

    // panel
    var panel = $('#panel');
    if (stop < 0) { panel.hidden = true; return; }
    var opened = false;
    if (panel.hidden) { panel.hidden = false; swapContent = true; opened = true; }
    var s = STOPS[stop];
    $('#panelNum').textContent = 'STOP ' + s.num + ' / 06';
    $('#panelTitle').textContent = s.title;
    panel.setAttribute('aria-label', s.name);
    var prev = $('#prevBtn');
    prev.hidden = stop === 0;
    if (stop > 0) prev.textContent = '← ' + STOPS[stop - 1].name;
    $('#nextBtn').hidden = stop === 5;
    if (stop < 5) $('#nextLabel').textContent = 'Next stop: ' + STOPS[stop + 1].name;
    $('#endBtn').hidden = stop !== 5;

    if (swapContent) {
      var body = $('#pbody');
      body.innerHTML = '';
      body.scrollTop = 0;
      body.appendChild($('#tpl-' + s.id).content.cloneNode(true));
      if (s.id === 'work') renderWork();
      if (s.id === 'stack') renderStack();
      if (opened) panel.focus({ preventScroll: true });
    }
  }

  function renderWork() {
    var body = $('#pbody'), p = PROJECTS[state.project];
    var chips = $('[data-slot="projectChips"]', body);
    chips.innerHTML = '';
    PROJECTS.forEach(function (pr, i) {
      var b = el('button', 'sel' + (i === state.project ? ' on' : ''), pr.name);
      b.dataset.action = 'project'; b.dataset.index = i;
      chips.appendChild(b);
    });
    ['domain', 'mono', 'cat', 'name', 'desc', 'outcome'].forEach(function (k) { $('[data-slot="' + k + '"]', body).textContent = p[k]; });
    body.querySelectorAll('[data-tint="bg"]').forEach(function (n) { n.style.background = p.tint; });
    var tags = $('[data-slot="tags"]', body); tags.innerHTML = '';
    p.tags.forEach(function (t) { tags.appendChild(el('span', 'chip', t)); });
    $('[data-slot="url"]', body).href = p.url;
  }

  function renderStack() {
    var body = $('#pbody'), t = STACK[state.tab];
    $('[data-slot="tabName"]', body).textContent = t.name;
    var chips = $('[data-slot="tabChips"]', body); chips.innerHTML = '';
    STACK.forEach(function (tb, i) {
      var b = el('button', 'sel' + (i === state.tab ? ' on' : ''), tb.name);
      b.dataset.action = 'tab'; b.dataset.index = i;
      chips.appendChild(b);
    });
    var items = $('[data-slot="items"]', body); items.innerHTML = '';
    t.items.forEach(function (it) {
      var c = el('div');
      c.style.cssText = 'padding:14px 16px;border-radius:12px;border:1px solid rgba(33,28,24,.12);background:#FFFDF9;display:flex;align-items:center;justify-content:space-between;gap:12px';
      var l = el('div'); l.style.cssText = 'display:flex;flex-direction:column;gap:3px';
      var n = el('span', null, it[0]); n.style.cssText = 'font-size:14px;font-weight:600';
      var d = el('span', 'mono', it[1]); d.style.cssText = 'font-size:11px;color:#6B5E53';
      l.append(n, d);
      var dot = el('span'); dot.style.cssText = 'width:8px;height:8px;border-radius:50%;background:#3F8F5F;flex-shrink:0';
      c.append(l, dot);
      items.appendChild(c);
    });
  }


  /* ================= CONTACT (Resend via /api/contact) ================= */
  function send() {
    var name = $('#cf-name'), email = $('#cf-email'), msg = $('#cf-msg');
    var btn = $('#cf-send'), status = $('#cf-status');
    if (!name || !email || !msg) return;
    if (!name.value.trim() || !email.value.trim() || !msg.value.trim()) {
      status.textContent = 'Name, email, and message are all needed.';
      return;
    }
    btn.disabled = true;
    status.textContent = 'Sending...';
    fetch('/api/contact', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ name: name.value.trim(), email: email.value.trim(), message: msg.value.trim() })
    }).then(function (res) {
      if (!res.ok) throw new Error('send failed');
      name.value = ''; email.value = ''; msg.value = '';
      status.textContent = 'Message received. I will be in touch within 24 to 48 hours.';
    }).catch(function () {
      btn.disabled = false;
      status.textContent = 'That did not send. Email chanel@stackdstudiosai.com instead.';
    });
  }

  /* ================= EVENTS ================= */
  root.addEventListener('click', onClick);
  cleanups.push(function () { root.removeEventListener('click', onClick); });
  function onClick(e) {
    var t = e.target.closest('[data-action]');
    if (!t) return;
    var a = t.dataset.action;
    if (a === 'enter') enter();
    else if (a === 'contact') { if (state.scene === 'inside') go(5); else enter(5); }
    else if (a === 'exit') exit();
    else if (a === 'go') go(+t.dataset.stop);
    else if (a === 'start') {
      var n = Object.keys(state.visited).length, i = 0;
      while (i < 5 && state.visited[i]) i++;
      go(n >= 6 ? 0 : i);
    }
    else if (a === 'map') { state.stop = -1; render(); }
    else if (a === 'prev') { if (state.stop > 0) go(state.stop - 1); }
    else if (a === 'next') { if (state.stop < 5) go(state.stop + 1); }
    else if (a === 'project') { state.project = +t.dataset.index; renderWork(); }
    else if (a === 'tab') { state.tab = +t.dataset.index; renderStack(); }
    else if (a === 'send') send();
  }

  // Keyboard: Esc closes the panel, then leaves the system. Arrows step between stops.
  function onKey(e) {
    if (state.scene !== 'inside') return;
    var tag = (e.target && e.target.tagName) || '';
    if (tag === 'INPUT' || tag === 'TEXTAREA') return;
    if (e.key === 'Escape') { if (state.stop >= 0) { state.stop = -1; render(); } else exit(); }
    else if (e.key === 'ArrowRight' && state.stop >= 0 && state.stop < 5) go(state.stop + 1);
    else if (e.key === 'ArrowLeft' && state.stop > 0) go(state.stop - 1);
  }
  document.addEventListener('keydown', onKey);
  cleanups.push(function () { document.removeEventListener('keydown', onKey); });

  // Deep link: add #inside to the URL to skip the office.
  if (location.hash === '#inside') {
    office.classList.add('zoom');
    state.zooming = false;
    officeScene.hidden = true;
    mount.appendChild($('#tpl-inside').content.cloneNode(true));
    state.scene = 'inside';
    buildInside();
  }
  fit();

  return function () { cleanups.forEach(function (fn) { fn(); }); };
}
